groupInfo:
  groupID: idВашейГруппы 
  groupToken: 'ТутВашТокен' #ВНИМАНИЕ! Не делитесь ни с кем вашим токеном, иначе это даст доступ к боту
settings:
  delay: 20 #ВНИМАНИЕ! Не ставьте слишком низкие числа ( не ниже 5)
  disableGroupListener: true #Плагин будет игнорировать сообщения от групп